--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/benjaminXYZ/BedrockCoins
build-by-default: true
branches:
- master
projects:
  BedrockCoins:
    path: "ben\BedrockCoins\BedrockCoins"
...
